---
title: "Some notes on the 4 noble truths"
author: "Jinhuizi Fu"
date: 2020-09-08T10:30:00-05:00
output: html_document
categories: ["thoughts"]
tags: ["thoughts"]
---

I've just started to study a course on Coursera called *"Buddhism and Modern Psychology"*. I find it very interesting. The purpose of the course is not all about religion, but rather with the help of buddhism and modern psychology, how to find happiness and peace in life. 

The first topic is about the 4 noble truths:

1. the truth of suffering
2. the cause of suffering
3. the cessation of suffering
4. the Noble Eightfold Path

Here are some points from the course that I find interesting:

* What our brain tells us might not be the truth. The instructor showed an experiment: what do you see in ambiguous pictures? The pictures could be viewed, for example, as either a rope or a snake. The answer is about 50/50 when there is no music. However, if there's horrifying background music playing, a lot more people will choose the horrifying view, i.e. a snake. This tells us that when the brain is stressed, it tends to interpret the world as more negative. It might have helped our ancestors survive the dangerous world, but for us, we need to know that our brain can lie to us and things might not as bad as it seems.

* We suffer because we are attached to certain things. We put so much effort into pursuing happiness, but happiness evaporates so easily, which leaves us feeling empty and drives us wanting for more. This theory actually aligns with natural selection, for ones that are restless have a bigger chance of passing on their genes into the next generation. 

* Happiness is highly correlated with dopamine level. When we get rewarded, there's a dopamine spike, and we feel ecstatic at that moment. An experiment with monkeys shows that if we give a monkey juice, this will lead to a dopamine spike. If we train the monkey to anticipate juice when a certain bulb lights up, the lighting of the bulb will lead to a even higher dopamine spike, followed by a smaller dopamine spike when the monkey actually gets the juice. However, if the monkey does not get juice later, his dopamine level will drop below usual level. This explains why getting let down is an awful feeling, and expectation management is very important for our mind. 

Reference: 
Course link on Coursera: https://www.coursera.org/learn/science-of-meditation/home/welcome
